using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace CozyBoard {
 public sealed class WorkshopShopSmoke:MonoBehaviour {
  readonly List<string> results=new();string report;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
  static void Boot(){if(Environment.GetCommandLineArgs().Contains("--cozy-shop-smoke")){foreach(var camera in FindObjectsByType<Camera>(FindObjectsSortMode.None))camera.enabled=false;new GameObject("Background shop checks").AddComponent<WorkshopShopSmoke>();}}
  void Check(bool ok,string message){if(!ok)throw new Exception(message);results.Add("PASS "+message);}
  IEnumerator Start(){report=Path.Combine(Application.temporaryCachePath,"shop-smoke-report.txt");yield return null;yield return null;var run=Run();while(true){bool more;object current=null;try{more=run.MoveNext();if(more)current=run.Current;}catch(Exception ex){results.Add("FAIL "+ex);File.WriteAllLines(report,results);Application.Quit(1);yield break;}if(!more)break;yield return current;}File.WriteAllLines(report,results);Application.Quit(0);}
  IEnumerator Run(){
   var g=FindFirstObjectByType<WorkshopGameMode>();var shop=g.Shop;var c=g.Controller;g.Audio.MusicSource.mute=true;g.Audio.EffectsSource.mute=true;shop.ResetShop();g.NewOrder();g.Experience.Continue();yield return new WaitForSeconds(.8f);
   Check(g.Experience.MenuArt!=null,"Menu has dedicated atelier artwork");var laptop=GameObject.Find("Cozy workshop laptop");Check(laptop.transform.localScale.x>1.3f,"Laptop has larger desk footprint");var grey=GameObject.Find("Closed sculpted lid").GetComponent<Renderer>().sharedMaterial.GetColor("_BaseColor");Check(Mathf.Abs(grey.r-grey.b)<.05f,"Laptop body uses neutral grey");
   foreach(var id in new[]{"Screwdriver","KeyPuller","Tweezers"}){var tool=c.Lookup[id];Physics.SyncTransforms();var point=c.ViewCamera.WorldToScreenPoint(tool.transform.TransformPoint(tool.BoundsCenter));var hits=new System.Collections.Generic.List<UnityEngine.EventSystems.RaycastResult>();UnityEngine.EventSystems.EventSystem.current.RaycastAll(new UnityEngine.EventSystems.PointerEventData(UnityEngine.EventSystems.EventSystem.current){position=point},hits);Check(!hits.Any(h=>h.module is UnityEngine.UI.GraphicRaycaster),"No UI intercepts desk tool "+id+" "+string.Join(",",hits.Select(h=>h.gameObject.name)));c.BeginDragAt(point);Check(g.Tools.Selected==id,"Pointer ray selects desk tool "+id);g.Tools.Deselect();}
   var laptopHome=laptop.transform.position;var laptopPoint=(Vector2)c.ViewCamera.WorldToScreenPoint(laptopHome+Vector3.up*.25f);Physics.SyncTransforms();g.Menu.SelectTool(1);Check(shop.BeginLaptopMove(laptopPoint),"Laptop can be picked up in move mode");shop.MoveLaptop(laptopPoint+new Vector2(-180,-90));Check(Vector3.Distance(laptopHome,laptop.transform.position)>.2f&&!shop.IsOpen,"Moving laptop changes its position without opening shop");shop.EndLaptopMove(true);Check(laptop.transform.position==laptopHome,"Escape restores laptop position");shop.BeginLaptopMove(laptopPoint);shop.MoveLaptop(laptopPoint+new Vector2(-100,0));shop.EndLaptopMove(false);Check(shop.Data.laptopPlaced&&shop.Data.laptopPosition==laptop.transform.position,"Placed laptop position is stored for saves");g.Menu.SelectTool(0);
   Check(shop.Ready&&GameObject.Find("Cozy workshop laptop"),"Physical laptop and catalogue initialized");
   var boxes=FindObjectsByType<WorkshopSupply>(FindObjectsSortMode.None);Check(boxes.Length==1&&boxes[0].GetComponent<WorkshopSupplyMotion>().Arrived,"Supply carton finishes arrival animation");
   shop.Open();Check(shop.IsOpen&&g.Menu.InputBlocked,"Laptop catalogue blocks workbench input");int credits=shop.Data.credits;Check(shop.Purchase(4)&&shop.Data.credits==credits-75&&shop.Data.stock[4]==1,"Buying a tactile set deducts credits and adds stock");Check(shop.Data.selected[1]==4&&g.Audio.SwitchVoice==1,"Selected switch affects sound profile");
   Check(shop.Purchase(8)&&shop.Data.selected[2]==8,"Purchased lavender caps become active");
   int held=shop.Data.credits;shop.Data.credits=0;Check(!shop.Purchase(5)&&shop.Data.stock[5]==0,"Unaffordable purchase cannot create stock");shop.Data.credits=held;int beforeReturn=shop.Data.credits;Check(shop.Refund(3)&&shop.Data.credits==beforeReturn+60&&shop.Data.stock[3]==0,"Unused set refund returns Tık without duplicating inventory");Check(!shop.Refund(3),"An empty inventory cannot be refunded twice");shop.Close();
   foreach(var p in c.Items.Where(x=>x.Stage is 1 or 2).OrderBy(x=>x.Stage).ToArray())Check(c.PaintAt(p.Stage,c.Lookup["Case"].transform.TransformPoint(p.Slot)),"PCB and plate install using one kit");
   yield return new WaitForSeconds(.8f);Check(shop.Data.stock[0]==0&&shop.Data.used[0],"PCB kit consumed once for PCB and plate");Check(FindObjectsByType<WorkshopSupply>(FindObjectsSortMode.None).Single().Stage==3,"Outgoing carton leaves before next stage settles");
   foreach(var p in c.Items.Where(x=>x.Stage==3).ToArray())c.PaintAt(3,c.Lookup["Case"].transform.TransformPoint(p.Slot));
   Check(shop.Data.stock[4]==0&&shop.Data.used[1],"61 switches consume exactly one selected set");Check(!shop.Select(3),"Installed switch choice cannot change mid-keyboard");
   foreach(var p in c.Items.Where(x=>x.Stage==4).ToArray())c.PaintAt(4,c.Lookup["Case"].transform.TransformPoint(p.Slot));yield return new WaitForSeconds(.8f);Check(g.Completed&&FindObjectsByType<WorkshopSupply>(FindObjectsSortMode.None).Length==0,"All supply cartons animate away after assembly");
   Check(GameObject.Find("Closed sculpted lid")!=null,"Laptop has closed sculpted lid");
   var cap=c.Items.First(x=>x.Stage==4);var capVisual=cap.Visual.transform;
   Physics.SyncTransforms();c.BeginDragAt(c.ViewCamera.WorldToScreenPoint(cap.transform.TransformPoint(cap.BoundsCenter)));yield return new WaitForSeconds(.05f);Check(capVisual.localPosition.y<-.005f&&capVisual.localScale.y<1,"Key press visibly travels downward and compresses");yield return new WaitForSeconds(.5f);Check(capVisual.localPosition.sqrMagnitude<.000001f&&Vector3.Distance(capVisual.localScale,Vector3.one)<.0001f,"Key spring returns exactly to resting pose");
   var sw=c.Items.First(x=>x.Stage==3&&Vector2.Distance(new Vector2(x.Slot.x,x.Slot.z),new Vector2(cap.Slot.x,cap.Slot.z))<.15f);
   g.Tools.TrySelect(c.Lookup["Tweezers"]);Check(!g.Tools.TryRemove(sw),"Switch cannot be removed through fitted keycap");
   var puller=c.Lookup["KeyPuller"].transform;var pullerHome=puller.position;var tweezers=c.Lookup["Tweezers"].transform;var tweezersHome=tweezers.position;g.Press(cap);yield return new WaitForSeconds(.03f);g.Tools.TrySelect(c.Lookup["KeyPuller"]);Check(g.Tools.TryRemove(cap),"Key puller starts removal");yield return new WaitForSeconds(.25f);Check(Vector3.Distance(puller.position,pullerHome)>.3f&&g.Tools.Busy,"Key puller travels to the selected cap");yield return new WaitForSeconds(1.4f);Check(puller.position==pullerHome,"Key puller returns to its desk position");Check(!cap.Fitted&&!g.Tools.Busy&&capVisual.localPosition==Vector3.zero&&capVisual.localScale==Vector3.one,"Removing a pressed cap cancels its spring and returns it to stock");
   g.Tools.TrySelect(c.Lookup["Tweezers"]);Check(g.Tools.TryRemove(sw),"Switch puller removes uncovered switch");yield return new WaitForSeconds(.25f);Check(Vector3.Distance(tweezers.position,tweezersHome)>.3f&&g.Tools.Busy,"Switch puller travels to the selected switch");yield return new WaitForSeconds(1.4f);Check(tweezers.position==tweezersHome,"Switch puller returns to its desk position");Check(!sw.Fitted,"Removed switch returns to stock");g.Tools.Deselect();
   Check(c.PaintAt(3,c.Lookup["Case"].transform.TransformPoint(sw.Slot)),"Removed switch can be reinstalled");Check(c.PaintAt(4,c.Lookup["Case"].transform.TransformPoint(cap.Slot)),"Removed cap can be reinstalled");yield return new WaitForSeconds(.8f);
   var driver=c.Lookup["Screwdriver"];var driverHome=driver.transform.position;var driverRotation=driver.transform.rotation;
   for(int i=0;i<4;i++){Check(g.Tools.UseScrew(i),"Corner screw starts tightening "+i);yield return new WaitForSeconds(.55f);var screw=c.Lookup["Case"].transform.Find("Case screw "+i);var tip=driver.transform.TransformPoint(driver.BoundsCenter+Vector3.forward*driver.BoundsSize.z*.5f);Check(Vector3.Distance(tip,screw.position+screw.up*.023f)<.015f,"Screwdriver tip stays seated on screw "+i);var turn=driver.transform.rotation;yield return new WaitForSeconds(.2f);Check(Quaternion.Angle(turn,driver.transform.rotation)>10,"Screwdriver visibly rotates on screw "+i);yield return new WaitForSeconds(1.1f);Check(driver.transform.position==driverHome&&Quaternion.Angle(driver.transform.rotation,driverRotation)<.01f&&!g.Tools.Busy,"Screwdriver returns to desk "+i);}
   g.Tools.UseScrew(0);yield return new WaitForSeconds(.25f);g.Tools.ResetState();Check(driver.transform.position==driverHome&&!g.Tools.Busy,"Interrupted tool animation restores original pose");g.Tools.Tightened=15;Check(g.Tools.Tightened==15,"All four case screws fasten");
   g.Menu.SelectTool(3);g.Painter.SendMessage("ConfigureStudioUI");g.Painter.EditorPanel.SetActive(true);g.Painter.PalettePanel.SetActive(true);Canvas.ForceUpdateCanvases();var a=(RectTransform)g.Painter.PalettePanel.transform;var b=(RectTransform)g.Painter.EditorSurface.transform.parent.parent.parent;var aa=new Vector3[4];var bb=new Vector3[4];a.GetWorldCorners(aa);b.GetWorldCorners(bb);Check(Mathf.Abs(aa[0].y-bb[0].y)<.5f&&Mathf.Abs(aa[1].y-bb[1].y)<.5f,"Paint panels share exact top and bottom edges");g.Painter.CloseEditor();g.Menu.SelectTool(0);
   string saved=g.SerializeProgress();g.RestoreProgress(saved);Check(g.Tools.Tightened==15,"Save restores fastened screws");Check(g.Completed&&shop.Data.selected[1]==4&&shop.Data.selected[2]==8&&shop.Data.stock[4]==0,"Save restores fitted parts, choices and consumed inventory");
   int money=shop.Data.credits;int order=g.OrderNumber;g.Experience.BeginPacking();Check(g.Experience.PackStep==1,"Physical packing starts at open carton");for(int step=1;step<=3;step++){g.Experience.AdvancePacking();yield return new WaitForSeconds(.9f);Check(g.Experience.PackStep==step+1,"Packing animation completes step "+step);}g.Experience.AdvancePacking();yield return new WaitForSeconds(1.3f);Check(!g.Experience.Packing&&g.OrderNumber==order+1,"Shipment transition restores workspace and starts next order");Check(shop.Data.credits==money+240,"Shipment reward funds future orders");g.Menu.ClosePanels();Check(!shop.HasSupply(1)&&g.Stock.Length==0,"Next order requires fresh materials after kit consumption");Check(shop.Purchase(1)&&shop.HasSupply(1),"Laptop restocks a new PCB variant");yield return new WaitForSeconds(.8f);Check(FindObjectsByType<WorkshopSupply>(FindObjectsSortMode.None).Single().GetComponent<WorkshopSupplyMotion>().Arrived,"Purchased material returns in animated carton");
  }
 }
}
