using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace CozyBoard {
 public sealed class WorkshopShopSmoke:MonoBehaviour {
  readonly List<string> results=new();string report;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
  static void Boot(){if(Environment.GetCommandLineArgs().Contains("--cozy-shop-smoke")){foreach(var camera in FindObjectsByType<Camera>(FindObjectsSortMode.None))camera.enabled=false;new GameObject("Background shop checks").AddComponent<WorkshopShopSmoke>();}}
  void Check(bool ok,string message){if(!ok)throw new Exception(message);results.Add("PASS "+message);}
  IEnumerator Start(){report=Path.Combine(Application.temporaryCachePath,"shop-smoke-report.txt");yield return null;yield return null;var run=Run();while(true){bool more;object current=null;try{more=run.MoveNext();if(more)current=run.Current;}catch(Exception ex){results.Add("FAIL "+ex);File.WriteAllLines(report,results);Application.Quit(1);yield break;}if(!more)break;yield return current;}File.WriteAllLines(report,results);Application.Quit(0);}
  IEnumerator Run(){
   var g=FindFirstObjectByType<WorkshopGameMode>();var shop=g.Shop;var c=g.Controller;g.Audio.MusicSource.mute=true;g.Audio.EffectsSource.mute=true;shop.ResetShop();g.OrderNumber=1;g.LastDelivery=null;g.DeliveryMail.Clear();g.NewOrder();g.Experience.Continue();yield return new WaitForSeconds(.8f);
   Check(g.Experience.MenuArt!=null,"Menu has dedicated atelier artwork");var laptop=GameObject.Find("Cozy workshop laptop");Check(laptop.transform.localScale.x>1.3f,"Laptop has larger desk footprint");var grey=GameObject.Find("Closed sculpted lid").GetComponent<Renderer>().sharedMaterial.GetColor("_BaseColor");Check(Mathf.Abs(grey.r-grey.b)<.05f,"Laptop body uses neutral grey");
   foreach(var id in new[]{"Screwdriver","KeyPuller","Tweezers"}){var tool=c.Lookup[id];Physics.SyncTransforms();var point=c.ViewCamera.WorldToScreenPoint(tool.transform.TransformPoint(tool.BoundsCenter));var hits=new System.Collections.Generic.List<UnityEngine.EventSystems.RaycastResult>();UnityEngine.EventSystems.EventSystem.current.RaycastAll(new UnityEngine.EventSystems.PointerEventData(UnityEngine.EventSystems.EventSystem.current){position=point},hits);Check(!hits.Any(h=>h.module is UnityEngine.UI.GraphicRaycaster),"No UI intercepts desk tool "+id+" "+string.Join(",",hits.Select(h=>h.gameObject.name)));c.BeginDragAt(point);Check(g.Tools.Selected==id,"Pointer ray selects desk tool "+id);g.Tools.Deselect();}
   var laptopHome=laptop.transform.position;var laptopPoint=(Vector2)c.ViewCamera.WorldToScreenPoint(laptopHome+Vector3.up*.25f);Physics.SyncTransforms();g.Menu.SelectTool(1);Check(shop.BeginLaptopMove(laptopPoint),"Laptop can be picked up in move mode");shop.MoveLaptop(laptopPoint+new Vector2(-180,-90));Check(Vector3.Distance(laptopHome,laptop.transform.position)>.2f&&!shop.IsOpen,"Moving laptop changes its position without opening shop");shop.EndLaptopMove(true);Check(laptop.transform.position==laptopHome,"Escape restores laptop position");shop.BeginLaptopMove(laptopPoint);shop.MoveLaptop(laptopPoint+new Vector2(-100,0));shop.EndLaptopMove(false);Check(shop.Data.laptopPlaced&&shop.Data.laptopPosition==laptop.transform.position,"Placed laptop position is stored for saves");g.Menu.SelectTool(0);
   Check(shop.Ready&&GameObject.Find("Cozy workshop laptop"),"Physical laptop and catalogue initialized");
   var boxes=FindObjectsByType<WorkshopSupply>(FindObjectsSortMode.None);Check(boxes.Length==1&&boxes[0].GetComponent<WorkshopSupplyMotion>().Arrived,"Supply carton finishes arrival animation");
   int[,] expected={{2,0,0},{1,2,1},{0,1,2}};
   for(int orderId=1;orderId<=3;orderId++)for(int switchId=3;switchId<=5;switchId++){
    var result=WorkshopOrders.Evaluate(orderId,switchId);
    Check(result.matches==expected[orderId-1,switchId-3]&&result.reward==240+result.matches*30,"Customer/switch match and reward "+orderId+"/"+switchId);
   }
   Check(WorkshopOrders.For(4).Name==WorkshopOrders.For(1).Name,"Customer rotation is stable across orders");
   for(int orderId=1;orderId<=3;orderId++){
    g.OrderNumber=orderId;g.Menu.ShowOrder();Canvas.ForceUpdateCanvases();g.Menu.OrderBody.ForceMeshUpdate();Check(!g.Menu.OrderBody.isTextOverflowing,"Request fits order card for customer "+orderId);
    g.LastDelivery=WorkshopOrders.Evaluate(orderId,3);g.Menu.RefreshOrder();Canvas.ForceUpdateCanvases();g.Menu.OrderBody.ForceMeshUpdate();Check(!g.Menu.OrderBody.isTextOverflowing,"Reaction fits delivery card for customer "+orderId);
   }
   g.LastDelivery=null;g.OrderNumber=1;g.Menu.ClosePanels();
   Check(shop.ClearLaptopPosition(laptop.transform.position),"Laptop starts in a clear footprint");
   foreach(var point in new[]{new Vector3(7.35f,.025f,0),new Vector3(6.35f,.025f,4),new Vector3(7.4f,.025f,-3.7f),Vector3.zero})Check(!shop.ClearLaptopPosition(point),"Laptop rejects carton, open lid, tool mat or keyboard overlap "+point);
   var good=laptop.transform.position;shop.Data.laptopPlaced=true;shop.Data.laptopPosition=new Vector3(7.35f,.025f,0);shop.Restore(shop.Data);Check(shop.ClearLaptopPosition(laptop.transform.position),"Old overlapping laptop placement migrates to a clear space");
   var mat=GameObject.Find("Linen tool rest").GetComponent<Renderer>();Check(mat.bounds.min.x>5.05f&&mat.sharedMaterial.shader.name=="CozyBoard/WorkMat","Textured tool mat sits fully outside the main cutting mat");
   var status=GameObject.Find("Workshop progress paper").GetComponent<RectTransform>();Check(status.anchorMin.y==0&&!status.GetComponent<UnityEngine.UI.Image>(),"Progress is compact bottom text without a large background");
   Check(Resources.Load<Material>("Materials/WorkMat").shader.name=="CozyBoard/WorkMat","Cutting mat shader is included in the player");
   shop.Open();Check(shop.IsOpen&&g.Menu.InputBlocked,"Laptop catalogue blocks workbench input");int credits=shop.Data.credits;Check(shop.Purchase(4)&&shop.Data.credits==credits-75&&shop.Data.stock[4]==1,"Buying a tactile set deducts credits and adds stock");Check(shop.Data.selected[1]==4&&g.Audio.SwitchVoice==1,"Selected switch affects sound profile");
   Check(shop.Purchase(8)&&shop.Data.selected[2]==8,"Purchased lavender caps become active");
   int held=shop.Data.credits;shop.Data.credits=0;Check(!shop.Purchase(5)&&shop.Data.stock[5]==0,"Unaffordable purchase cannot create stock");shop.Data.credits=held;int beforeReturn=shop.Data.credits;Check(shop.Refund(3)&&shop.Data.credits==beforeReturn+60&&shop.Data.stock[3]==0,"Unused set refund returns Tık without duplicating inventory");Check(!shop.Refund(3),"An empty inventory cannot be refunded twice");shop.Close();
   foreach(var p in c.Items.Where(x=>x.Stage is 1 or 2).OrderBy(x=>x.Stage).ToArray())Check(c.PaintAt(p.Stage,c.Lookup["Case"].transform.TransformPoint(p.Slot)),"PCB and plate install using one kit");
   yield return new WaitForSeconds(.8f);Check(shop.Data.stock[0]==0&&shop.Data.used[0],"PCB kit consumed once for PCB and plate");Check(FindObjectsByType<WorkshopSupply>(FindObjectsSortMode.None).Single().Stage==3,"Outgoing carton leaves before next stage settles");
   var feedback=g.Audio.transform.Find("Assembly feedback").GetComponent<AudioSource>();
   Check(feedback&&feedback.gameObject!=g.Audio.EffectsSource.gameObject&&!feedback.GetComponent<AudioLowPassFilter>(),"Assembly feedback is isolated from the typing sound filter");
   Check(Resources.Load<AudioClip>("Assembly/ScrewTurn")&&Resources.Load<AudioClip>("Assembly/ScrewStop"),"Screw friction and torque clips are included in the player");
   float effectVolume=g.Audio.EffectsVolume;g.Audio.SetEffects(0);Check(feedback.volume==0,"Effects slider also mutes assembly feedback");g.Audio.SetEffects(effectVolume);
   var firstSwitch=c.Items.First(x=>x.Stage==3);var socket=c.Lookup["Case"].transform.TransformPoint(firstSwitch.Slot);
   Check(c.PaintAt(3,socket),"Switch installation starts");yield return new WaitForSeconds(.21f);
   Check(firstSwitch.Visual.transform.localPosition.y>.04f,"Switch meets visible resistance before seating");
   Check(!c.PaintAt(3,socket),"Repeated pressure cannot install a second switch in the same socket");
   yield return new WaitForSeconds(.4f);Check(firstSwitch.Visual.transform.localPosition==Vector3.zero&&firstSwitch.Visual.transform.localRotation==Quaternion.identity,"Switch settles exactly into its socket");
   foreach(var p in c.Items.Where(x=>x.Stage==3).ToArray())c.PaintAt(3,c.Lookup["Case"].transform.TransformPoint(p.Slot));
   Check(shop.Data.stock[4]==0&&shop.Data.used[1],"61 switches consume exactly one selected set");Check(!shop.Select(3),"Installed switch choice cannot change mid-keyboard");
   foreach(var p in c.Items.Where(x=>x.Stage==4).ToArray())c.PaintAt(4,c.Lookup["Case"].transform.TransformPoint(p.Slot));yield return new WaitForSeconds(.8f);Check(g.Completed&&FindObjectsByType<WorkshopSupply>(FindObjectsSortMode.None).Length==0,"All supply cartons animate away after assembly");
   Check(GameObject.Find("Closed sculpted lid")!=null,"Laptop has closed sculpted lid");
   var cap=c.Items.First(x=>x.Stage==4);var capVisual=cap.Visual.transform;
   Physics.SyncTransforms();c.BeginDragAt(c.ViewCamera.WorldToScreenPoint(cap.transform.TransformPoint(cap.BoundsCenter)));yield return new WaitForSeconds(.05f);Check(capVisual.localPosition.y<-.005f&&capVisual.localScale==Vector3.one,"Key press travels downward without deforming the cap");yield return new WaitForSeconds(.5f);Check(capVisual.localPosition.sqrMagnitude<.000001f&&Vector3.Distance(capVisual.localScale,Vector3.one)<.0001f,"Key spring returns exactly to resting pose");
   g.Press(cap);yield return new WaitForSeconds(.13f);g.Press(cap);yield return new WaitForSeconds(.045f);Check(capVisual.localPosition.y<-.07f&&capVisual.localScale==Vector3.one,"Rapid repeat tap restarts the downstroke instead of being ignored");yield return new WaitForSeconds(.4f);
   var keyboard=UnityEngine.InputSystem.Keyboard.current??UnityEngine.InputSystem.InputSystem.AddDevice<UnityEngine.InputSystem.Keyboard>();UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState(UnityEngine.InputSystem.Key.A));yield return null;g.Press(cap,false,keyboard.aKey);yield return new WaitForSeconds(.2f);Check(capVisual.localPosition.y<-.09f,"Holding a physical key keeps the cap depressed");UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState());yield return new WaitForSeconds(.3f);Check(capVisual.localPosition==Vector3.zero&&capVisual.localScale==Vector3.one,"Releasing the physical key restores its exact rest pose");
   var sw=c.Items.First(x=>x.Stage==3&&Vector2.Distance(new Vector2(x.Slot.x,x.Slot.z),new Vector2(cap.Slot.x,cap.Slot.z))<.15f);
   g.Tools.TrySelect(c.Lookup["Tweezers"]);Check(!g.Tools.TryRemove(sw),"Switch cannot be removed through fitted keycap");
   var puller=c.Lookup["KeyPuller"].transform;var pullerHome=puller.position;var tweezers=c.Lookup["Tweezers"].transform;var tweezersHome=tweezers.position;g.Press(cap);yield return new WaitForSeconds(.03f);g.Tools.TrySelect(c.Lookup["KeyPuller"]);Check(g.Tools.TryRemove(cap),"Key puller starts removal");yield return new WaitForSeconds(.25f);Check(Vector3.Distance(puller.position,pullerHome)>.3f&&g.Tools.Busy,"Key puller travels to the selected cap");yield return new WaitForSeconds(1.4f);Check(puller.position==pullerHome,"Key puller returns to its desk position");Check(!cap.Fitted&&!g.Tools.Busy&&capVisual.localPosition==Vector3.zero&&capVisual.localScale==Vector3.one,"Removing a pressed cap cancels its spring and returns it to stock");
   g.Tools.TrySelect(c.Lookup["Tweezers"]);Check(g.Tools.TryRemove(sw),"Switch puller removes uncovered switch");yield return new WaitForSeconds(.25f);Check(Vector3.Distance(tweezers.position,tweezersHome)>.3f&&g.Tools.Busy,"Switch puller travels to the selected switch");yield return new WaitForSeconds(1.4f);Check(tweezers.position==tweezersHome,"Switch puller returns to its desk position");Check(!sw.Fitted,"Removed switch returns to stock");g.Tools.Deselect();
   Check(c.PaintAt(3,c.Lookup["Case"].transform.TransformPoint(sw.Slot)),"Removed switch can be reinstalled");Check(c.PaintAt(4,c.Lookup["Case"].transform.TransformPoint(cap.Slot)),"Removed cap can be reinstalled");yield return new WaitForSeconds(.8f);
   var driver=c.Lookup["Screwdriver"];var driverHome=driver.transform.position;var driverRotation=driver.transform.rotation;
   for(int i=0;i<4;i++){Check(g.Tools.UseScrew(i),"Corner screw starts tightening "+i);yield return new WaitForSeconds(.55f);var screw=c.Lookup["Case"].transform.Find("Case screw "+i);var tip=driver.transform.TransformPoint(driver.BoundsCenter+Vector3.forward*driver.BoundsSize.z*.5f);Check(Vector3.Distance(tip,screw.position+screw.up*.023f)<.015f,"Screwdriver tip stays seated on screw "+i);var turn=driver.transform.rotation;yield return new WaitForSeconds(.2f);Check(Quaternion.Angle(turn,driver.transform.rotation)>10,"Screwdriver visibly rotates on screw "+i);for(float deadline=Time.realtimeSinceStartup+3;g.Tools.Busy&&Time.realtimeSinceStartup<deadline;)yield return null;Check(driver.transform.position==driverHome&&Quaternion.Angle(driver.transform.rotation,driverRotation)<.01f&&!g.Tools.Busy,"Screwdriver returns to desk "+i);}
   Check(g.Tools.Tightened==15,"Four completed torque actions fasten all screws");g.Tools.UseScrew(0);yield return new WaitForSeconds(1.9f);Check(g.Tools.Tightened==14,"A complete reverse turn loosens only the selected screw");
   g.Tools.UseScrew(0);yield return new WaitForSeconds(.65f);g.Tools.ResetState();Check(driver.transform.position==driverHome&&!g.Tools.Busy,"Interrupted tool animation restores original pose");Check(c.Lookup["Case"].transform.Find("Case screw 0").localRotation==Quaternion.identity,"Interrupted screw rotation resets cleanly");g.Tools.Tightened=15;Check(g.Tools.Tightened==15,"All four case screws fasten");
   g.Menu.SelectTool(3);g.Painter.SendMessage("ConfigureStudioUI");g.Painter.EditorPanel.SetActive(true);g.Painter.PalettePanel.SetActive(true);Canvas.ForceUpdateCanvases();var a=(RectTransform)g.Painter.PalettePanel.transform;var b=(RectTransform)g.Painter.EditorSurface.transform.parent.parent.parent;var aa=new Vector3[4];var bb=new Vector3[4];a.GetWorldCorners(aa);b.GetWorldCorners(bb);Check(Mathf.Abs(aa[0].y-bb[0].y)<.5f&&Mathf.Abs(aa[1].y-bb[1].y)<.5f,"Paint panels share exact top and bottom edges");g.Painter.CloseEditor();g.Menu.SelectTool(0);
   Check(g.Testing&&!g.Testing.Passed,"Finished assembly still needs key testing");g.Experience.BeginPacking();Check(!g.Experience.Packing&&g.Testing.Active,"Packing routes an untested board into the test stage");
   foreach(var key in c.Items.Where(x=>x.Stage==4))g.Press(key);Check(g.Testing.Count==60&&!g.Testing.Passed,"Test detects exactly one unseated switch");
   string faultId=g.Testing.LooseSwitch;g.RestoreProgress(g.SerializeProgress());Check(g.Testing.Count==60&&g.Testing.LooseSwitch==faultId,"Unfinished test and fault survive save/reload");g.Testing.Begin();
   var loose=c.Lookup[g.Testing.LooseSwitch];var looseCap=c.Items.First(x=>x.Stage==4&&Vector2.Distance(new Vector2(x.Slot.x,x.Slot.z),new Vector2(loose.Slot.x,loose.Slot.z))<.15f);
   g.Tools.TrySelect(c.Lookup["KeyPuller"]);Check(g.Tools.TryRemove(looseCap),"Faulty keycap can be lifted for repair");yield return new WaitForSeconds(1.5f);
   g.Tools.TrySelect(c.Lookup["Tweezers"]);Check(g.Tools.TryRemove(loose),"Unseated switch can be extracted");yield return new WaitForSeconds(1.5f);g.Tools.Deselect();
   c.PaintAt(3,c.Lookup["Case"].transform.TransformPoint(loose.Slot));c.PaintAt(4,c.Lookup["Case"].transform.TransformPoint(looseCap.Slot));yield return new WaitForSeconds(.7f);
   g.Testing.Begin();g.Press(looseCap);Check(g.Testing.Passed,"Reinstalled switch passes its retest");g.Press(looseCap);Check(g.Testing.Count==61,"Repeated key presses cannot inflate test progress");g.Testing.Removed(looseCap);Check(!g.Testing.Passed&&g.Testing.Count==60,"Removing a checked key invalidates its test result");g.Press(looseCap);g.Testing.End();
   var portrait=g.Menu.OrderPanel.transform.Find("Photo paper/Drawn customer").GetComponent<UnityEngine.UI.RawImage>();
   for(int n=1;n<=3;n++){g.OrderNumber=n;g.Menu.RefreshOrder();Check(Mathf.Abs(portrait.uvRect.x-(n-1)/3f)<.001f&&portrait.texture==Resources.Load<Texture2D>("Customers/Portraits"),"Distinct portrait for customer "+n);}g.OrderNumber=1;g.Menu.RefreshOrder();
   string saved=g.SerializeProgress();g.RestoreProgress(saved);Check(g.Tools.Tightened==15,"Save restores fastened screws");Check(g.Testing.Passed,"Save restores repaired switch and all 61 tested keys");Check(g.Completed&&shop.Data.selected[1]==4&&shop.Data.selected[2]==8&&shop.Data.stock[4]==0,"Save restores fitted parts, choices and consumed inventory");
   int money=shop.Data.credits;int order=g.OrderNumber;var cameraBefore=c.ViewTarget;var boardBefore=c.Lookup["Case"].transform.position;g.Experience.BeginPacking();Check(g.Experience.PackStep==1,"Physical packing starts at open carton");yield return null;
   Check(!c.Lookup["Screwdriver"].gameObject.activeSelf&&!GameObject.Find("Screwdriver_ContactShadow").GetComponent<Renderer>().enabled,"Packing hides tools and their contact shadows");
   g.Experience.CancelPacking();Check(c.ViewTarget==cameraBefore&&c.Lookup["Case"].transform.position==boardBefore&&c.Lookup["Screwdriver"].gameObject.activeSelf,"Cancelling packing restores board, camera and tools");g.Experience.BeginPacking();for(int step=1;step<=3;step++){g.Experience.AdvancePacking();yield return new WaitForSeconds(.9f);Check(g.Experience.PackStep==step+1,"Packing animation completes step "+step);var carton=GameObject.Find("Shipping carton").GetComponent<WorkshopCarton>();if(step==2)Check(carton.Wrap.activeSelf&&Quaternion.Angle(carton.Wrap.transform.Find("Left paper hinge").localRotation,Quaternion.identity)<.01f&&Quaternion.Angle(carton.Wrap.transform.Find("Right paper hinge").localRotation,Quaternion.identity)<.01f,"Both tissue wings finish folded over the keyboard");if(step==3)Check(carton.Tape.activeSelf&&carton.Tape.transform.localScale.z>4,"Sealing tape reaches the full parcel depth");}g.Experience.AdvancePacking();yield return new WaitForSeconds(1.3f);Check(!g.Experience.Packing&&g.OrderNumber==order+1,"Shipment transition restores workspace and starts next order");Check(shop.Data.credits==money+240,"Shipment reward funds future orders");
   Check(g.LastDelivery!=null&&g.LastDelivery.pending&&g.LastDelivery.order==order&&g.LastDelivery.matches==0,"Receipt evaluates shipped switches before starting next order");
   Check(!g.Menu.OrderPanel.activeSelf&&!shop.IsOpen,"Delivery announces mail without forcing a modal open");
   int paid=shop.Data.credits;string receiptSave=g.SerializeProgress();g.RestoreProgress(receiptSave);g.Menu.ShowOrder();Check(g.LastDelivery.pending&&g.Menu.OrderName.text.Contains("Deniz")&&shop.UnreadMail==1,"Unread mail survives reload while next order remains accessible");
   shop.OpenMail();Check(shop.MailOpen&&!g.LastDelivery.pending&&shop.UnreadMail==0&&shop.Data.credits==paid,"Reading customer mail marks it read without paying twice");shop.Close();
   string readSave=g.SerializeProgress();g.RestoreProgress(readSave);Check(g.DeliveryMail.Count==1&&!g.DeliveryMail[0].pending,"Read customer mail remains archived after reload");
   var oldMail=JsonUtility.FromJson<WorkshopGameMode.SaveData>(readSave);oldMail.version=8;oldMail.mail=null;oldMail.receipt.pending=true;g.RestoreProgress(JsonUtility.ToJson(oldMail));Check(g.DeliveryMail.Count==1&&shop.UnreadMail==1,"Version 8 receipt migrates to one unread laptop mail");g.RestoreProgress(readSave);
   var second=WorkshopOrders.Evaluate(2,3);g.DeliveryMail.Add(second);shop.OpenMail();Check(!second.pending,"Newest message opens in the laptop inbox");shop.ReadMail(0);Check(shop.MailOpen&&g.DeliveryMail[0].order==1&&shop.Data.credits==paid,"Older customer mail remains readable without duplicate rewards");shop.Close();
   var legacy=JsonUtility.FromJson<WorkshopGameMode.SaveData>(g.SerializeProgress());legacy.version=6;legacy.receipt=null;g.RestoreProgress(JsonUtility.ToJson(legacy));Check(g.LastDelivery==null&&g.OrderNumber==order+1&&shop.Data.credits==paid,"Version 6 saves preserve order and wallet without a receipt");
g.Menu.ClosePanels();Check(!shop.HasSupply(1)&&g.Stock.Length==0,"Next order requires fresh materials after kit consumption");Check(shop.Purchase(1)&&shop.HasSupply(1),"Laptop restocks a new PCB variant");yield return new WaitForSeconds(.8f);Check(FindObjectsByType<WorkshopSupply>(FindObjectsSortMode.None).Single().GetComponent<WorkshopSupplyMotion>().Arrived,"Purchased material returns in animated carton");
  }
 }
}
